#include "inputTakingUnit.h"
#include "term.h"
#include "constantpart.h"
#include "outputUnit.h"
#include "constantpart.h"
#include "powerpart.h"
#include "variablefunctionpart.h"
#include "coefficientpart.h"
